test: off
version: "{build}"
platform: Any CPU
init:
    - cmd: msbuild /version
environment:
    COVERALLS_REPO_TOKEN:
        secure: LJtAmPTMf2oAcdDxgNBN7bd9k9KVngraj8Ui7cA1lOWvaCVZKJEC+r2mSrVnNuBT
build_script:
    - cmd: build.cmd
after_build:
    - cmd: coveralls-upload.cmd
artifacts:
    - path: reports
    - path: history
